build:
  image: golang:1.5
  commands:
    - make deps
    - make build
    - make test

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-newrelic
    when:
      branch: master

plugin:
  name: New Relic
  desc: Deploy software with New Relic
  type: publish
  image: plugins/drone-newrelic
  labels:
    - ruby
    - newrelic
