sudo: required
services:
  - docker
language: go
go:
  - 1.5
install:
  - docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
script:
  - make deps
  - make build
  - make test
  - docker build -t $DOCKER_IMAGE_NAME .
  - if [ ! -z "$TRAVIS_TAG" ]; then docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$TRAVIS_TAG; fi && docker push $DOCKER_IMAGE_NAME
env:
  global:
    - secure: vpq1TgOCz2zhoA0xeUShcdfszNp3LLWlfi1JW7hoOGzEgqYQBapv6KcLUABzG2jTFwL0G1ufEo4hI9l7K5gIImsHESo5qaicxutp44FHR+kRHWXqMnLtUn9rc5Ok8Fz+HW8oiZ0BeqTZWEcWytAPLWpYHTc3iVE9eM0waO0WraqWHk8FzDKfAW1ARG/Sb4q8IWfN8xVvbLUaGk37a+dppDUWuv+TwCP8b37dFVIucQIxOYtbHRW+dPD7qoCGcp9VLeoJJWI3nqcm39D+hMG6nJ/pGylgCu4hOVlfrUZ/cNGPdg0FBF+Zex3fWIAReFRxTQYQ74CwCWX278lL91bqJYaYduy16fEQwt2JpLCkE0TgwlKINSASub5DVoL1uMvvVh760gY39Z19QPoyMjXBp2U/HJH9WuNZKv6Vz0i7Knaozfuh9G8NL7F80i+vTbamCZfCIHwOoi5UwKX5pxxHxnIG1F6ZcxCf7Br7pbEVgcQvqG6yFAY/D4irdo6Zr4bgqMAMltXfY6hlYwx02EL+V9zz4Rw7O0m73LeIplF1tjfBdOn85y+aD34pjiH7Ws61UdMrZoKN78E+8j6DnwTpXyk9HFWQ5se3EWnSDo66lSI7NZIRWDtAhfcbqODUuuWJ8l3KiaGqNDfab5r34bYp08/EArjw37cwfmNze7qu2+E=
    - DOCKER_IMAGE_NAME=glaszig/drone-newrelic
